package com.medinsights.patient_service.entities;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * ChatConversation Entity
 * Stores chatbot conversation history with patients
 * Messages stored as JSONB array: [{"role": "user", "content": "...", "timestamp": "2026-02-09T10:30:00Z"}]
 * 
 * Architecture: Stored in Patient Service (PostgreSQL) for centralized data management
 * Used by: Chatbot Service for context-aware responses
 */
@Entity
@Table(name = "chat_conversations")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EntityListeners(AuditingEntityListener.class)
public class ChatConversation {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * Patient associated with this conversation
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "patient_id", nullable = false)
    private Patient patient;

    /**
     * Session ID to group related messages in a single conversation
     * Generated by chatbot frontend, used to maintain conversation context
     */
    @Column(name = "session_id", nullable = false, unique = true)
    private String sessionId;

    /**
     * Conversation title (auto-generated from first message or user-defined)
     * Example: "Consultation sur douleur thoracique"
     */
    @Column(name = "title", length = 500)
    private String title;

    /**
     * Messages stored as JSONB array
     * Format: [
     *   {"role": "user", "content": "J'ai une douleur au thorax", "timestamp": "2026-02-09T10:30:00Z"},
     *   {"role": "assistant", "content": "Je comprends votre préoccupation...", "timestamp": "2026-02-09T10:30:05Z"}
     * ]
     */
    @Column(name = "messages", columnDefinition = "TEXT")
    private String messages;

    /**
     * Total number of messages in conversation (for quick stats)
     */
    @Column(name = "message_count")
    private Integer messageCount = 0;

    /**
     * When the conversation started
     */
    @Column(name = "started_at")
    private LocalDateTime startedAt;

    /**
     * When the last message was sent
     */
    @Column(name = "last_message_at")
    private LocalDateTime lastMessageAt;

    /**
     * Conversation status
     * Values: ACTIVE, ARCHIVED, DELETED
     */
    @Column(name = "status", length = 20)
    private String status = "ACTIVE";

    /**
     * Tags for categorization (comma-separated)
     * Example: "urgence,cardiologie,consultation"
     */
    @Column(name = "tags", length = 500)
    private String tags;

    /**
     * Audit: When conversation was created
     */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Audit: When conversation was last updated
     */
    @LastModifiedDate
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * Helper: Check if conversation is active
     */
    public boolean isActive() {
        return "ACTIVE".equals(status);
    }

    /**
     * Helper: Check if conversation is archived
     */
    public boolean isArchived() {
        return "ARCHIVED".equals(status);
    }
}
